// ============================================================
// PDF Privacy Report Generator
// Uses jsPDF to create a downloadable privacy report
// ============================================================

import jsPDF from 'jspdf';
import type { ScannedBreach, ScannedDataBroker } from './scanner';
import type { DiscoveredAccount, TrackedSubscription } from './extensionBridge';
import type { DarkWebAlert, ScoreSnapshot } from '../store/useStore';

interface ReportData {
  emails: string[];
  privacyScore: number;
  scoreHistory: ScoreSnapshot[];
  breaches: ScannedBreach[];
  dataBrokers: ScannedDataBroker[];
  accounts: DiscoveredAccount[];
  subscriptions: TrackedSubscription[];
  darkWebAlerts: DarkWebAlert[];
}

function formatDate(d: string | Date): string {
  return new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

export function generatePrivacyReport(data: ReportData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addPage = () => {
    doc.addPage();
    y = margin;
  };

  const checkPageBreak = (neededSpace: number) => {
    if (y + neededSpace > 270) addPage();
  };

  // ─── Cover ───
  doc.setFillColor(8, 8, 12);
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), 'F');

  // Title
  doc.setTextColor(245, 245, 247);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('Privacy Report', margin, y + 15);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 160);
  doc.text(`Generated by Vanish on ${formatDate(new Date())}`, margin, y + 24);
  doc.text(`Emails: ${data.emails.join(', ')}`, margin, y + 30);
  y += 45;

  // ─── Privacy Score ───
  doc.setFillColor(20, 20, 28);
  doc.roundedRect(margin, y, contentWidth, 40, 3, 3, 'F');

  const scoreColor = data.privacyScore > 70 ? [34, 197, 94] : data.privacyScore > 40 ? [249, 115, 22] : [239, 68, 68];
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  doc.text(`${data.privacyScore}`, margin + 12, y + 27);

  doc.setFontSize(12);
  doc.setTextColor(150, 150, 160);
  doc.text('/100', margin + 35, y + 27);

  doc.setFontSize(10);
  doc.setTextColor(200, 200, 210);
  doc.text('Privacy Score', margin + 55, y + 20);

  doc.setFontSize(9);
  doc.setTextColor(150, 150, 160);
  const riskLevel = data.privacyScore > 70 ? 'Low Risk' : data.privacyScore > 40 ? 'Medium Risk' : 'High Risk';
  doc.text(riskLevel, margin + 55, y + 28);
  y += 50;

  // ─── Summary Stats ───
  const stats = [
    { label: 'Data Breaches', value: data.breaches.length, color: [239, 68, 68] },
    { label: 'Data Brokers', value: data.dataBrokers.filter((b) => b.status === 'found').length, color: [249, 115, 22] },
    { label: 'Dark Web Alerts', value: data.darkWebAlerts.filter((a) => !a.resolved).length, color: [168, 120, 255] },
    { label: 'Linked Accounts', value: data.accounts.length, color: [124, 106, 239] },
    { label: 'Active Subscriptions', value: data.subscriptions.filter((s) => s.active).length, color: [34, 197, 94] },
  ];

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(245, 245, 247);
  doc.text('Summary', margin, y);
  y += 8;

  const colW = contentWidth / stats.length;
  for (let i = 0; i < stats.length; i++) {
    const x = margin + i * colW;
    doc.setFillColor(20, 20, 28);
    doc.roundedRect(x + 1, y, colW - 2, 22, 2, 2, 'F');

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(stats[i].color[0], stats[i].color[1], stats[i].color[2]);
    doc.text(`${stats[i].value}`, x + colW / 2, y + 10, { align: 'center' });

    doc.setFontSize(6);
    doc.setTextColor(150, 150, 160);
    doc.text(stats[i].label, x + colW / 2, y + 17, { align: 'center' });
  }
  y += 30;

  // ─── Score History ───
  if (data.scoreHistory.length > 1) {
    checkPageBreak(50);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(245, 245, 247);
    doc.text('Score History', margin, y);
    y += 8;

    // Simple line chart
    const chartH = 30;
    const chartW = contentWidth;
    doc.setFillColor(20, 20, 28);
    doc.roundedRect(margin, y, chartW, chartH, 2, 2, 'F');

    const points = data.scoreHistory;
    const maxScore = 100;
    for (let i = 1; i < points.length; i++) {
      const x1 = margin + ((i - 1) / (points.length - 1)) * chartW;
      const x2 = margin + (i / (points.length - 1)) * chartW;
      const y1 = y + chartH - (points[i - 1].score / maxScore) * (chartH - 4) - 2;
      const y2 = y + chartH - (points[i].score / maxScore) * (chartH - 4) - 2;
      doc.setDrawColor(124, 106, 239);
      doc.setLineWidth(0.5);
      doc.line(x1, y1, x2, y2);
    }

    y += chartH + 8;
  }

  // ─── Breaches Section ───
  if (data.breaches.length > 0) {
    checkPageBreak(30);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(245, 245, 247);
    doc.text(`Data Breaches (${data.breaches.length})`, margin, y);
    y += 8;

    for (const breach of data.breaches) {
      checkPageBreak(20);
      doc.setFillColor(20, 20, 28);
      doc.roundedRect(margin, y, contentWidth, 14, 2, 2, 'F');

      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(245, 245, 247);
      doc.text(breach.name, margin + 4, y + 5);

      const sevColors: Record<string, number[]> = {
        critical: [239, 68, 68], high: [249, 115, 22],
        medium: [234, 179, 8], low: [59, 130, 246],
      };
      const sc = sevColors[breach.severity] || [150, 150, 150];
      doc.setTextColor(sc[0], sc[1], sc[2]);
      doc.setFont('helvetica', 'normal');
      doc.text(breach.severity.toUpperCase(), margin + contentWidth - 4, y + 5, { align: 'right' });

      doc.setTextColor(150, 150, 160);
      doc.setFontSize(7);
      doc.text(`${breach.email} · ${breach.date} · ${breach.dataTypes.slice(0, 4).join(', ')}`, margin + 4, y + 11);

      y += 16;
    }
    y += 5;
  }

  // ─── Dark Web Alerts ───
  if (data.darkWebAlerts.length > 0) {
    checkPageBreak(30);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(245, 245, 247);
    doc.text(`Dark Web Alerts (${data.darkWebAlerts.length})`, margin, y);
    y += 8;

    for (const alert of data.darkWebAlerts.slice(0, 15)) {
      checkPageBreak(16);
      doc.setFillColor(20, 20, 28);
      doc.roundedRect(margin, y, contentWidth, 12, 2, 2, 'F');

      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(168, 120, 255);
      doc.text(alert.source, margin + 4, y + 5);

      doc.setTextColor(150, 150, 160);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.text(`${alert.email} · ${alert.type} · ${alert.severity}`, margin + 4, y + 10);

      y += 14;
    }
    y += 5;
  }

  // ─── Data Brokers ───
  const exposedBrokers = data.dataBrokers.filter((b) => b.status === 'found');
  if (exposedBrokers.length > 0) {
    checkPageBreak(30);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(245, 245, 247);
    doc.text(`Data Broker Exposures (${exposedBrokers.length})`, margin, y);
    y += 8;

    for (const broker of exposedBrokers.slice(0, 20)) {
      checkPageBreak(12);
      doc.setFillColor(20, 20, 28);
      doc.roundedRect(margin, y, contentWidth, 10, 2, 2, 'F');

      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(249, 115, 22);
      doc.text(broker.name, margin + 4, y + 6);

      doc.setTextColor(150, 150, 160);
      doc.setFont('helvetica', 'normal');
      doc.text(broker.dataTypes.slice(0, 3).join(', '), margin + contentWidth / 2, y + 6);

      y += 12;
    }
    y += 5;
  }

  // ─── Subscriptions ───
  const activeSubs = data.subscriptions.filter((s) => s.active);
  if (activeSubs.length > 0) {
    checkPageBreak(30);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(245, 245, 247);
    doc.text(`Active Subscriptions (${activeSubs.length})`, margin, y);
    y += 8;

    const monthlyTotal = activeSubs.reduce((sum, s) => {
      if (s.frequency === 'yearly') return sum + s.amount / 12;
      return sum + s.amount;
    }, 0);

    doc.setFontSize(10);
    doc.setTextColor(34, 197, 94);
    doc.text(`Estimated monthly spend: $${monthlyTotal.toFixed(2)}`, margin, y);
    y += 8;

    for (const sub of activeSubs.slice(0, 20)) {
      checkPageBreak(12);
      doc.setFillColor(20, 20, 28);
      doc.roundedRect(margin, y, contentWidth, 10, 2, 2, 'F');

      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(245, 245, 247);
      doc.text(sub.name, margin + 4, y + 6);

      doc.setTextColor(34, 197, 94);
      doc.setFont('helvetica', 'normal');
      const curr = sub.currency === 'EUR' ? '\u20AC' : sub.currency === 'GBP' ? '\u00A3' : '$';
      doc.text(`${curr}${sub.amount.toFixed(2)}/${sub.frequency === 'yearly' ? 'yr' : 'mo'}`, margin + contentWidth - 4, y + 6, { align: 'right' });

      y += 12;
    }
  }

  // ─── Footer ───
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 110);
    doc.text(
      `Vanish Privacy Report · Page ${p}/${pageCount} · ${formatDate(new Date())}`,
      pageWidth / 2,
      285,
      { align: 'center' },
    );
  }

  doc.save(`vanish-privacy-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
